version: '3.8'

services:
  backend:
    build:
      context: ./SzakdolgozatBackend
      dockerfile: Dockerfile
    image: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://szakdoga-postgresql-db.ch4mw0qwom8d.eu-north-1.rds.amazonaws.com:5432/szakdoga
      SPRING_DATASOURCE_USERNAME: szakdoga
      SPRING_DATASOURCE_PASSWORD: szakdoga
      SPRING_DATA_MONGODB_URI: mongodb+srv://szakdoga:szakdoga@szakdoga.przm6.mongodb.net/?retryWrites=true&w=majority/szakdoga
    depends_on:
      - postgres
      - mongo
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./szakdolgozat-frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: szakdoga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asd1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: